import Providers from '@/components/Providers';
import Navbar from '@/components/navbar/Navbar';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const raleway = Raleway({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Lashes Studio By Boochita',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={raleway.className}>
        <Providers>
          <Navbar />
          <div className='container mx-auto px-4 md:px-6 lg:px-8 xl:px-0'>
            {children}
          </div>
        </Providers>
        <div id='portal-root'></div>
        <ToastContainer
          toastClassName='customToast'
          className='toastContainer'
          hideProgressBar
          pauseOnFocusLoss={false}
        />
      </body>
    </html>
  );
}
